# SPDX-License-Identifier: MIT
#
---
# The following file enables recreating a templated output dir by executing:
#   mk-scaffold clone "https://gitlab.com/cappysan/scaffolds/asustor-template.git" --input-file .answers.yml --output-dir output
answers:
  - include: "~/.config/scaffold/answers.yml"
    optional: True

  - author: "Julien Lecomte"
  - email: "julien@cappysan.dev"

  - project_name: "cappysan-certbot"
  - project_slug: "cappysan-certbot"
  - project_url: "https://gitlab.com/cappysan/asustor/certbot"
  - project_description: "Let's Encrypt certbot."

  - has_documentation: False
  - documentation_url: ""

  - has_ci: True
  - has_pages: False
  - has_releases: True

  - has_precommit: True
  - has_precommit_codespell: True
  - has_precommit_nitpick: True

  - license: "MIT"
  - version: "5.2.2-r28"
  - version_style: "semver-rev"
  - copyright_string: "Cappysan, Julien Lecomte, and contributors"

  - keep_placeholders: False

  - template_url: "https://gitlab.com/cappysan/scaffolds/asustor-template"
  - template_version: "1.1.0-r4"

  - creation_year: "2026"
  - last_update: "2026-06-06 23:17:19"

  - maintainer: "Cappysan"
  - developer: "Cappysan"

  - app_name: "Persistence"
  - cfg_name: "persistence"
  - cappysan_name: "cappysan-persistence"
  - asustor_name: "asustor-persistence"

  - apk_description: "Enable changing /etc configuration files on boot"
  - has_adm_desktop: True

  # Items without visible questions:
  - depends: '"python3(>=3.10.0)"'
  - adm_desktop_customizable: False
  - boot_priority_start: 60
  - boot_priority_stop: 40
  - has_upstream: False
