/* _AS_STRINGS */
_AS_STRINGS = {};

/*CERTBOT*/
_AS_STRINGS.CERTBOT = {};
_AS_STRINGS.CERTBOT.APP_TITLE           = 'Certbot';
_AS_STRINGS.CERTBOT.TAB_CERTIFICATE     = 'Certificate';
_AS_STRINGS.CERTBOT.TAB_SETTINGS        = 'Settings';
_AS_STRINGS.CERTBOT.LABEL_DOMAINS       = 'Domains';
_AS_STRINGS.CERTBOT.LABEL_PROVIDER      = 'Provider';
_AS_STRINGS.CERTBOT.LABEL_CMDLINE       = 'Command line';
_AS_STRINGS.CERTBOT.SECTION_SETTINGS    = 'Settings';
_AS_STRINGS.CERTBOT.SECTION_CREDENTIALS = 'Credentials';
_AS_STRINGS.CERTBOT.SECTION_ADVANCED    = 'Advanced';
_AS_STRINGS.CERTBOT.BTN_RENEW           = 'Renew';
_AS_STRINGS.CERTBOT.BTN_DOWNLOAD = 'Download';
