#!/usr/bin/env sh
# SPDX-License-Identifier: MIT
#
# The shell variable $RENEWED_LINEAGE will point to the config live subdirectory,
# (eg: "/etc/letsencrypt/live/example.com") containing the new certificates and
# keys;
# The shell variable $RENEWED_DOMAINS will contain a space-delimited list
# of renewed certificate domains.
#
# Even if the UI has a button to download the certificates, make them available
# via ssh or shared mount
#
. /usr/local/AppCentral/cappysan-certbot/.env.install
cd ${APKG_CFG_DIR:-/nonexistent} || exit 1
. ${APKG_PKG_DIR}/env

if test ! -f ${APKG_CFG_DIR}/certificates.zip; then
  exit 0
fi

mkdir -p /usr/builtin/webman/portal/downloads
rm -f /usr/builtin/webman/portal/downloads/*-certificates.zip || true
random=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 16)

ln -sf -T ${APKG_CFG_DIR}/certificates.zip /usr/builtin/webman/portal/downloads/${random}-certificates.zip
echo "${random}" > ${APKG_PKG_DIR}/random
exit 0
